//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkUserMapping
    {
        public int ID { get; set; }
        public int LinkID { get; set; }
        public bool Status { get; set; }
        public int UserID { get; set; }
        public string Note { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Link Link { get; set; }
        public virtual User User { get; set; }
    }
}
