//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int LinkID { get; set; }
        public string LinkHeading { get; set; }
        public string LinkDetail { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> LastVisited { get; set; }
        public Nullable<int> NoOfTimesVisited { get; set; }
        public int TopicID { get; set; }
        public string Link1 { get; set; }
        public string Description { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> IsVideoLink { get; set; }
    
        public virtual Topic Topic { get; set; }
    }
}
